// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dvgyuurpujadeyacfolp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2Z3l1dXJwdWphZGV5YWNmb2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDMwNjMsImV4cCI6MjA3MjMxOTA2M30.Y0fEqLILXN45lSAkak8A6ogts_ZF4KZLKPmK3J2bLkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);